In [1]:
import pandas as pd

In [2]:
#df = pd.read_csv('Shoe prices.csv')
df = pd.read_csv('test.csv')

In [3]:
total_rows = df.shape[0]
total_cols = df.shape[1]
print(f'Всего строк: {total_rows}')
print(f'Всего столбцов: {total_cols}')

Всего строк: 1459
Всего столбцов: 80

In [4]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   object
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   object
 6   Alley          107 non-null    object
 7   LotShape       1459 non-null   object
 8   LandContour    1459 non-null   object
 9   Utilities      1457 non-null   object
 10  LotConfig      1459 non-null   object
 11  LandSlope      1459 non-null   object
 12  Neighborhood   1459 non-null   object
 13  Condition1     1459 non-null   object
 14  Condition2     1459 non-null   object
 15  BldgType       1459 non-null   object
 16  HouseStyle     1459 non-null   object
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   object
 22  RoofMatl       1459 non-null   object
 23  Exterior1st    1458 non-null   object
 24  Exterior2nd    1458 non-null   object
 25  MasVnrType     1443 non-null   object
 26  MasVnrArea     1444 non-null   float64
 27  ExterQual      1459 non-null   object
 28  ExterCond      1459 non-null   object
 29  Foundation     1459 non-null   object
 30  BsmtQual       1415 non-null   object
 31  BsmtCond       1414 non-null   object
 32  BsmtExposure   1415 non-null   object
 33  BsmtFinType1   1417 non-null   object
 34  BsmtFinSF1     1458 non-null   float64
 35  BsmtFinType2   1417 non-null   object
 36  BsmtFinSF2     1458 non-null   float64
 37  BsmtUnfSF      1458 non-null   float64
 38  TotalBsmtSF    1458 non-null   float64
 39  Heating        1459 non-null   object
 40  HeatingQC      1459 non-null   object
 41  CentralAir     1459 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1457 non-null   float64
 48  BsmtHalfBath   1457 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1458 non-null   object
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1457 non-null   object
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    729 non-null    object
 58  GarageType     1383 non-null   object
 59  GarageYrBlt    1381 non-null   float64
 60  GarageFinish   1381 non-null   object
 61  GarageCars     1458 non-null   float64
 62  GarageArea     1458 non-null   float64
 63  GarageQual     1381 non-null   object
 64  GarageCond     1381 non-null   object
 65  PavedDrive     1459 non-null   object
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         3 non-null      object
 73  Fence          290 non-null    object
 74  MiscFeature    51 non-null     object
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1458 non-null   object
 79  SaleCondition  1459 non-null   object
dtypes: float64(11), int64(26), object(43)
memory usage: 912.0+ KB

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Id,1459.0,2190.000000,421.321334,1461.0,1825.50,2190.0,2554.50,2919.0
MSSubClass,1459.0,57.378341,42.746880,20.0,20.00,50.0,70.00,190.0
LotFrontage,1232.0,68.580357,22.376841,21.0,58.00,67.0,80.00,200.0
LotArea,1459.0,9819.161069,4955.517327,1470.0,7391.00,9399.0,11517.50,56600.0
OverallQual,1459.0,6.078821,1.436812,1.0,5.00,6.0,7.00,10.0
OverallCond,1459.0,5.553804,1.113740,1.0,5.00,5.0,6.00,9.0
YearBuilt,1459.0,1971.357779,30.390071,1879.0,1953.00,1973.0,2001.00,2010.0
YearRemodAdd,1459.0,1983.662783,21.130467,1950.0,1963.00,1992.0,2004.00,2010.0
MasVnrArea,1444.0,100.709141,177.625900,0.0,0.00,0.0,164.00,1290.0
BsmtFinSF1,1458.0,439.203704,455.268042,0.0,0.00,350.5,753.50,4010.0
BsmtFinSF2,1458.0,52.619342,176.753926,0.0,0.00,0.0,0.00,1526.0
BsmtUnfSF,1458.0,554.294925,437.260486,0.0,219.25,460.0,797.75,2140.0
TotalBsmtSF,1458.0,1046.117970,442.898624,0.0,784.00,988.0,1305.00,5095.0
1stFlrSF,1459.0,1156.534613,398.165820,407.0,873.50,1079.0,1382.50,5095.0
2ndFlrSF,1459.0,325.967786,420.610226,0.0,0.00,0.0,676.00,1862.0
LowQualFinSF,1459.0,3.543523,44.043251,0.0,0.00,0.0,0.00,1064.0
GrLivArea,1459.0,1486.045922,485.566099,407.0,1117.50,1432.0,1721.00,5095.0
BsmtFullBath,1457.0,0.434454,0.530648,0.0,0.00,0.0,1.00,3.0
BsmtHalfBath,1457.0,0.065202,0.252468,0.0,0.00,0.0,0.00,2.0
FullBath,1459.0,1.570939,0.555190,0.0,1.00,2.0,2.00,4.0
HalfBath,1459.0,0.377656,0.503017,0.0,0.00,0.0,1.00,2.0
BedroomAbvGr,1459.0,2.854010,0.829788,0.0,2.00,3.0,3.00,6.0
KitchenAbvGr,1459.0,1.042495,0.208472,0.0,1.00,1.0,1.00,2.0
TotRmsAbvGrd,1459.0,6.385195,1.508895,3.0,5.00,6.0,7.00,15.0
Fireplaces,1459.0,0.581220,0.647420,0.0,0.00,0.0,1.00,4.0
GarageYrBlt,1381.0,1977.721217,26.431175,1895.0,1959.00,1979.0,2002.00,2207.0
GarageCars,1458.0,1.766118,0.775945,0.0,1.00,2.0,2.00,5.0
GarageArea,1458.0,472.768861,217.048611,0.0,318.00,480.0,576.00,1488.0
WoodDeckSF,1459.0,93.174777,127.744882,0.0,0.00,0.0,168.00,1424.0
OpenPorchSF,1459.0,48.313914,68.883364,0.0,0.00,28.0,72.00,742.0
EnclosedPorch,1459.0,24.243317,67.227765,0.0,0.00,0.0,0.00,1012.0
3SsnPorch,1459.0,1.794380,20.207842,0.0,0.00,0.0,0.00,360.0
ScreenPorch,1459.0,17.064428,56.609763,0.0,0.00,0.0,0.00,576.0
PoolArea,1459.0,1.744345,30.491646,0.0,0.00,0.0,0.00,800.0
MiscVal,1459.0,58.167923,630.806978,0.0,0.00,0.0,0.00,17000.0
MoSold,1459.0,6.104181,2.722432,1.0,4.00,6.0,8.00,12.0
YrSold,1459.0,2007.769705,1.301740,2006.0,2007.00,2008.0,2009.00,2010.0

In [7]:
df.isna().sum()

Id                 0
MSSubClass         0
MSZoning           4
LotFrontage      227
LotArea            0
                ...
MiscVal            0
MoSold             0
YrSold             0
SaleType           1
SaleCondition      0
Length: 80, dtype: int64

In [8]:
df_new = df.dropna(axis=1, how='any')
print(f'до: {df.shape}')
print(f'после: {df_new.shape}')

до: (1459, 80)
после: (1459, 47)

In [9]:
df_new.isna().sum()

Id               0
MSSubClass       0
LotArea          0
Street           0
LotShape         0
LandContour      0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
Condition2       0
BldgType         0
HouseStyle       0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
RoofStyle        0
RoofMatl         0
ExterQual        0
ExterCond        0
Foundation       0
Heating          0
HeatingQC        0
CentralAir       0
Electrical       0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
PavedDrive       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
SaleCondition    0
dtype: int64

In [10]:
num_cols = []
for col in df.columns:
    temp_null_count = df[df[col].isnull()].shape[0]
    dt = str(df[col].dtype)
    if temp_null_count>0 and (dt=='float64' or dt=='int64'):
        num_cols.append(col)
        temp_perc = round((temp_null_count / total_rows) * 100.0, 2)
        print(f'Колонка {col}. Тип данных {dt}. Количество пустых значений {temp_null_count}, {temp_perc}%.')

Колонка LotFrontage. Тип данных float64. Количество пустых значений 227, 15.56%.
Колонка MasVnrArea. Тип данных float64. Количество пустых значений 15, 1.03%.
Колонка BsmtFinSF1. Тип данных float64. Количество пустых значений 1, 0.07%.
Колонка BsmtFinSF2. Тип данных float64. Количество пустых значений 1, 0.07%.
Колонка BsmtUnfSF. Тип данных float64. Количество пустых значений 1, 0.07%.
Колонка TotalBsmtSF. Тип данных float64. Количество пустых значений 1, 0.07%.
Колонка BsmtFullBath. Тип данных float64. Количество пустых значений 2, 0.14%.
Колонка BsmtHalfBath. Тип данных float64. Количество пустых значений 2, 0.14%.
Колонка GarageYrBlt. Тип данных float64. Количество пустых значений 78, 5.35%.
Колонка GarageCars. Тип данных float64. Количество пустых значений 1, 0.07%.
Колонка GarageArea. Тип данных float64. Количество пустых значений 1, 0.07%.

In [11]:
columns_to_replace = ['LotFrontage', 'GarageYrBlt']
for column in columns_to_replace:
    df[column] = df[column].fillna(0)

In [12]:
df.isna().sum()

Id               0
MSSubClass       0
MSZoning         4
LotFrontage      0
LotArea          0
                ..
MiscVal          0
MoSold           0
YrSold           0
SaleType         1
SaleCondition    0
Length: 80, dtype: int64

In [13]:
cols_to_drop = ['MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'BsmtFullBath', 'GarageCars', 'GarageArea', 'MSZoning', 'SaleType']
df.dropna(subset=cols_to_drop,inplace = True, axis = 0)
df.isna().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MiscVal          0
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
Length: 80, dtype: int64

In [14]:
df.columns = df.columns.str.lower()
df.columns

Index(['id', 'mssubclass', 'mszoning', 'lotfrontage', 'lotarea', 'street',
       'alley', 'lotshape', 'landcontour', 'utilities', 'lotconfig',
       'landslope', 'neighborhood', 'condition1', 'condition2', 'bldgtype',
       'housestyle', 'overallqual', 'overallcond', 'yearbuilt', 'yearremodadd',
       'roofstyle', 'roofmatl', 'exterior1st', 'exterior2nd', 'masvnrtype',
       'masvnrarea', 'exterqual', 'extercond', 'foundation', 'bsmtqual',
       'bsmtcond', 'bsmtexposure', 'bsmtfintype1', 'bsmtfinsf1',
       'bsmtfintype2', 'bsmtfinsf2', 'bsmtunfsf', 'totalbsmtsf', 'heating',
       'heatingqc', 'centralair', 'electrical', '1stflrsf', '2ndflrsf',
       'lowqualfinsf', 'grlivarea', 'bsmtfullbath', 'bsmthalfbath', 'fullbath',
       'halfbath', 'bedroomabvgr', 'kitchenabvgr', 'kitchenqual',
       'totrmsabvgrd', 'functional', 'fireplaces', 'fireplacequ', 'garagetype',
       'garageyrblt', 'garagefinish', 'garagecars', 'garagearea', 'garagequal',
       'garagecond', 'paveddrive', 'wooddecksf', 'openporchsf',
       'enclosedporch', '3ssnporch', 'screenporch', 'poolarea', 'poolqc',
       'fence', 'miscfeature', 'miscval', 'mosold', 'yrsold', 'saletype',
       'salecondition'],
      dtype='object')

In [15]:
df.duplicated().sum()

0

In [16]:
df.sample(10)

,id,mssubclass,mszoning,lotfrontage,lotarea,street,alley,lotshape,landcontour,utilities,...,screenporch,poolarea,poolqc,fence,miscfeature,miscval,mosold,yrsold,saletype,salecondition
721,2182,20,RL,85.0,11058,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
893,2354,20,RL,63.0,7500,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2007,New,Partial
1268,2729,60,RL,85.0,9350,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,7,2006,WD,Normal
1373,2834,60,RL,91.0,10984,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,New,Partial
919,2380,85,RL,0.0,8723,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,1,2007,WD,Normal
769,2230,80,RL,73.0,9802,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2008,WD,Normal
524,1985,120,RL,0.0,3940,Pave,NaN,Reg,Lvl,AllPub,...,144,0,NaN,NaN,NaN,0,8,2008,WD,Normal
1390,2851,60,RL,0.0,21533,Pave,NaN,IR2,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,8,2006,WD,Normal
189,1650,20,RL,60.0,7038,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdPrv,NaN,0,9,2009,WD,Abnorml
315,1776,20,RL,67.0,13070,Pave,NaN,Reg,Lvl,AllPub,...,255,0,NaN,NaN,NaN,0,10,2009,WD,Normal

In [17]:
new_dummies = pd.get_dummies(df['saletype'], prefix='saletype')
new_data = pd.concat([df, new_dummies], axis=1)
new_data.drop('saletype', axis=1, inplace=True)

In [18]:
new_data

,id,mssubclass,mszoning,lotfrontage,lotarea,street,alley,lotshape,landcontour,utilities,...,salecondition,saletype_COD,saletype_CWD,saletype_Con,saletype_ConLD,saletype_ConLI,saletype_ConLw,saletype_New,saletype_Oth,saletype_WD
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,Normal,0,0,0,0,0,0,0,0,1
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,Normal,0,0,0,0,0,0,0,0,1
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,Normal,0,0,0,0,0,0,0,0,1
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,Normal,0,0,0,0,0,0,0,0,1
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,Normal,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,Normal,0,0,0,0,0,0,0,0,1
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,Abnorml,0,0,0,0,0,0,0,0,1
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,Abnorml,0,0,0,0,0,0,0,0,1
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,Normal,0,0,0,0,0,0,0,0,1
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,Normal,0,0,0,0,0,0,0,0,1

In [19]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
new_data['lotarea_scaled'] = scaler.fit_transform(new_data[['lotarea']])

In [20]:
new_data

,id,mssubclass,mszoning,lotfrontage,lotarea,street,alley,lotshape,landcontour,utilities,...,saletype_COD,saletype_CWD,saletype_Con,saletype_ConLD,saletype_ConLI,saletype_ConLw,saletype_New,saletype_Oth,saletype_WD,lotarea_scaled
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,0,0,0,0,0,0,0,0,1,0.201014
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,0,0,0,0,0,0,1,0.253386
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,0,0,0,0,0,0,1,0.244733
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,0,0,0,0,0,0,1,0.168462
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,0,0,0,0,0,0,0,0,1,0.069994
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,0,0,0,0,0,0,1,0.009227
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,0,0,0,0,0,0,1,0.008395
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,0,0,0,0,0,0,1,0.366902
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,0,0,0,0,0,0,1,0.177629
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,0,0,0,0,0,0,1,0.161512